### ISSUE TITLE
Add support for Mitsubishi heatpumps

### ISSUE THREAD

**Issue by Allram** [Joolee/nl.joolee.homey.espeasy#11]
Hello,

Is it possible to add support for this Esp Easy plugin? https://espeasy.readthedocs.io/en/latest/Plugin/P093.html

I run it today, but with mqtt

**Comment by Joolee** [comment]
Can you;
* [add Homey as a controller](https://github.com/Joolee/nl.joolee.homey.espeasy/wiki/3.-Configure-Homey-as-controller), 
* [configure the device](https://github.com/Joolee/nl.joolee.homey.espeasy/wiki/6.-Add-sensor-to-Homey#create-or-configure-your-device) so Homey receives data
* Wait a few minutes
* Send me a crash report through the app settings

That way, I can see what information Homey receives.

**Comment by Joolee** [comment]
Hi @Allram Can you send me the requested information? If you already did through another channel, can you tickle my memory?

**Comment by Allram** [comment]
Sorry for this, I just used MQTT with homey instead of this.
Will see if i try to reflash the device when i have some time and send you the info.
