### ISSUE TITLE
Add support for MH-Z19

### ISSUE THREAD

**Issue by Allram** [Joolee/nl.joolee.homey.espeasy#12]
I would like to have support for the MH-Z19 device/plugin.

It allows readout of CO2, so you can build an indoor CO2 metering station :)

https://www.letscontrolit.com/wiki/index.php?title=%22CO2_Sensor_MH-Z19%22
https://espeasy.readthedocs.io/en/latest/Plugin/P049.html

**Comment by Joolee** [comment]
Hi Allram,

Can you follow the steps in [the wiki](https://github.com/Joolee/nl.joolee.homey.espeasy/wiki/Get-new-device-supported) and post the results here?

**Comment by Allram** [comment]
Attached is the .json file (Change the file ending from .txt to .json).

I can't find any app settings page for the app on Homey, so i can't send that log.


[json.txt](https://github.com/Joolee/nl.joolee.homey.espeasy/files/5005788/json.txt)

**Comment by Joolee** [comment]
In the Homey app, go to:
More > Apps > ESP Easy > Cogweel on the top right > Create diagnostics report
I don't really need the ID because I don't get that many reports :)

**Comment by Joolee** [comment]
You can test the latest version at https://homey.app/a/nl.joolee.homey.espeasy/test/
Can you test it for me? I'll put it live if it works.

**Comment by Allram** [comment]
Works great! Thanks :-D
![Screenshot_20200804_221407_app homey](https://user-images.githubusercontent.com/5573149/89340334-ddf22700-d69f-11ea-9041-c4a500e5f1a6.jpg)
