### ISSUE TITLE
Cannot add switches (since update?)

### ISSUE THREAD

**Issue by AlgemeneBuurman** [Joolee/nl.joolee.homey.espeasy#13]
Hallo,

Got one NodeMCU v3 running at a friends house. Tested en worked fine for weeks. Using 4 inputs with switches attached to it.

Since last week the ESPEasy status and switches had a red ! next to it. Cannot find module. It was accessible on the webinterface. Choose to delete all ESPEasy config en re-add it to the Homey. I can add the status and see it updating. But when i want to add buttons that configured on the ESP the next button in de homey wizard does'nt work. At the state selection.

What am i doing wrong?

**Comment by Joolee** [comment]
I suspect you're running into the same problem as Stefan [on the forum](https://community.athom.com/t/esp-easy/30381/32). Can you also try the [test version](https://homey.app/a/nl.joolee.homey.espeasy/test/)?

**Comment by AlgemeneBuurman** [comment]
Installed the testversion, now it hangs on the rotating ball
![Screenshot_20200724-131924](https://user-images.githubusercontent.com/40493634/88386348-7c34e180-cdb0-11ea-8536-00367f215efa.jpg) I will follow the forum discussion also

**Comment by Joolee** [comment]
I published a new test, could you try again?
https://homey.app/a/nl.joolee.homey.espeasy/test/

**Comment by AlgemeneBuurman** [comment]
The add wizard is finished and the button is added. I can't check it right now cause I'm not on location. Wel be checking next Monday.

Thanks!

**Comment by AlgemeneBuurman** [comment]
Alright, let my friend test on location, it works! Many thanks!
