### ISSUE TITLE
[REQUEST] LCD display support

### ISSUE THREAD

**Issue by MrBlue90** [Joolee/nl.joolee.homey.espeasy#14]
Dear developer,

First I would like to thank you for creating this app.
It really opened a complete new world for me in the domotics landscape!

I've been connecting my cheap RFID door opener to my nodeMCU and got it connected to Homey.
So far, so good..

Now I've been looking into LCD displays like these to display my alarm status: https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20200727125628&SearchText=ssd1306
They are supported in ESP Easy, but I don't believe there's a way to control them over Homey.

Would it be possible to add a display device so the lines can be set over a flow?
![image](https://user-images.githubusercontent.com/11852942/88593436-da3b2080-d05f-11ea-9d9c-1134f18b6553.png)

Thanks,
Rick

**Comment by Joolee** [comment]
I think I'll be able to make that work:
https://www.letscontrolit.com/wiki/index.php?title=OLEDDisplay

Can you test if you can use these commands?
[<taskname>].OLED,<row>,<col>,<text> 
[<taskname>].OLEDCMD,<value>
?

I want to be able to target a specific OLED display that is connected, otherwise, I will be sending commands to all of them...

**Comment by MrBlue90** [comment]
I currently don't own such a display yet. Want to make sure it's supported before ordering.
I was indeed looking into the commands, and since I receive an 'OK' from the webserver, I feel that at least that should be working.
Is there a way to see the values (virtually) that I shared over cmd?

**Comment by Joolee** [comment]
You might be able to see them in the log if you set logging to high. I don't know for sure though.

**Comment by MrBlue90** [comment]
It gave me this:
`15254991: HTTP: OLED,1,1,TestTextOnDisplay
15254994: Command: OLED`

So not really the outcome I was looking for.
I obviously can order a display at Ali, but it might take some time to get shipped.

**Comment by Joolee** [comment]
It looks good though. Worst case, you can use it by triggering custom rules or commands (#2) with Homey.

I can't make the <taskname> version give me an OK though, that's a bit weird.

**Comment by Joolee** [comment]
I have fixed issue #2 so in the next version, you can run custom commands on the unit.

I want to see the commands below working before I add the plugin as a device. I don't want a user to accidentally control multiple OLED displays, that would get confusing.
```
[<taskname>].OLED,<row>,<col>,<text> 
[<taskname>].OLEDCMD,<value>
```

I'll look into this a bit more some time but if you can confirm you got the commands above working, I'll make the plugin. Shouldn't be too much work now that I have action cards implemented.

**Comment by MrBlue90** [comment]
Great news!
I've received the displays and did some testing.

In fact, there seems to be a difference between OLED and OLED FRAMED and in my scenario, OLED FRAMED worked best so far.

By triggering the following URL, I get to change text on my display:
http://<IP>/control?cmd=OLEDFRAMEDCMD,<ROW>,<Text>

**Comment by Joolee** [comment]
Is there also a way to specifically control a single oled panel? Otherwise, I'll have to restrict the oled devices to a single one per unit.

**Comment by MrBlue90** [comment]
Beat me to it, but I don't believe you can connect more than one display.
https://espeasy.readthedocs.io/en/latest/Plugin/P036.html

**Comment by Joolee** [comment]
Decided not to implement this for now. It's a lot of work to implement the most used display plugins and they can all be controlled by just sending commands to the unit with the available action flowcard.
