### ISSUE TITLE
Invert value/state

### ISSUE THREAD

**Issue by MrBlue90** [Joolee/nl.joolee.homey.espeasy#17]
One of my door contact sensors are connected and the input is NC.
So in normal state, it's HIGH and when you open the door, it gets LOW.

When I add the switch in Homey, the default state is also HIGH, which is considered ALARM ON.
I might invert the input on the ESP side, however this means that if the intruder would cut the door contact sensor, it wouldn't trigger anything (stays LOW).
Is there a way to invert this state in the Homey device so HIGH = ALARM OFF and LOW = ALARM ON?

Let me know if screenshots would be useful.

**Comment by Joolee** [comment]
What is the name of the device type you use in Homey? I already implemented an invert option for all binary type devices I believe, you can find it in the advanced settings of the device. I might have missed one but it's quite easy to add if I know what driver to modify.

**Comment by MrBlue90** [comment]
Great!
I used Switch Input > Contact Alarm.

**Comment by Joolee** [comment]
Looks like I forgot it there. I can add it some time next week.

**Comment by Joolee** [comment]
Didn't exactly make it that week. Sorry about the (long) delay!
