### ISSUE TITLE
I really would like support for the PMS5003 sensor

### ISSUE THREAD

**Issue by ehofstede** [Joolee/nl.joolee.homey.espeasy#18]
I haven't requested a feature like this before, I hope I do it correctly...
Diagnostic ID from the ESP Easy app on Homey: 92e7571b-0e42-47c0-bd90-6fe9d6611150
[ESP1.txt](https://github.com/Joolee/nl.joolee.homey.espeasy/files/5078631/ESP1.txt)

The PMS5003 sensor measures particular matter in the air, in the sizes PM1, PM2.5 and PM10.
I'm using this sensor to make the ventilation system run on higher speeds whenever the particular matter increases beyond a specific limit. 
At this moment ESP easy triggers a flow (on high particular matter) on Homey (HTTP request) which changes a logical value. Homey has another flow which sets the ventilation system on high when this logical value is set to high.
And ESP easy triggers another flow (on low particular matter) on Homey (same sort HTTP request) which changes the logical value back to a low value.
Another flow on Homey sets the ventilation system to low when this logical value is set to low.

So, at the moment, the result is exactly what I have been looking for, so far so good, but I would like to be able to read the values of this sensor on Homey. Maybe also keep historical data somehow.
And if Homey has direct access to the values of this sensor, I can also simplify the flows...

Unfortunately I'm not a code guru, so I really hope that you are willing to help supporting this sensor.
Thanks in advance!

**Comment by Joolee** [comment]
It's not too hard to add but it will take some time because Homey doesn't support the PM1 and PM10 capabilities by default. I'll let you know when I've gotten around to adding it ;)

**Comment by Joolee** [comment]
Just created the icons:
https://github.com/Joolee/Homey-SVG-Icons/commit/bc0ce0028e061d719f45aaa47262093085d9a902
