### ISSUE TITLE
[REQUEST] Double click options

### ISSUE THREAD

**Issue by AlgemeneBuurman** [Joolee/nl.joolee.homey.espeasy#19]
Hi there,

I use the espeasy plugin for homey to add pulse switches around the house to flows. One pulse activates the connected flow, 4 switches per room. 

In the espeasy setup is a doubleclick option (also longpress option) is it possible to use it in flows? It doubles the amount of switch-actions per room. An makes doubleclick for all-off in that room possible.

Thanks!

**Comment by Joolee** [comment]
It's not posible yet, I don't know exactly what signals Homey receives when you configure the double and long-press. You can help me finding it out:

1. [Configure Homey as controller in your ESP Easy unit.](https://github.com/Joolee/nl.joolee.homey.espeasy/wiki/3.-Configure-Homey-as-controller) (If you haven't done so already)
2. Configure your switch the way you need it in ESP Easy
3. [Make sure it sends events to Homey](https://github.com/Joolee/nl.joolee.homey.espeasy/wiki/6.-Add-sensor-to-Homey)
4. Fiddle with your switch with single, double and long-click
5. Send me a crash report from the app settings page

Make sure to write down the settings you use and include here, together with the crash report ID's. Please also include the contents of your http://&lt;ESP IP&gt;/json file.

**Comment by Joolee** [comment]
Hi @AlgemeneBuurman I want to add this option as it shouldn't require much work. I do need the requested information from you though. Can you get around to supplying it?
I could help you out in Dutch if needed
