### ISSUE TITLE
Support distance sensor (ultrasone)

### ISSUE THREAD

**Issue by Thiemo89** [Joolee/nl.joolee.homey.espeasy#21]
Could you also add support for the ultrasone sensor? I like to use the value for activating some flows.  

9bc14ea8-1e61-4fd1-a4dd-5331c7732e10

thanks in advance!

**Comment by MrBlue90** [comment]
I would like to request the same thing.
To be specific, it would be this sensor:
https://www.letscontrolit.com/wiki/index.php?title=HC-SR04#Optional_settings

Thanks!

**Comment by CreateYourAccount-username** [comment]
Same here, I am putting HC-SR04 into an oil tank to keep track of the oil level. 
Homey report: bbc7bc37-6ab4-4bd8-8e7e-4d1c57e52a6a

Please see attachment for JSON file


[esp_easy_json.txt](https://github.com/Joolee/nl.joolee.homey.espeasy/files/6364707/esp_easy_json.txt)
