### ISSUE TITLE
Can't pair with ESP8266Wifi NanoMCU

### ISSUE THREAD

**Issue by LoenieVincia** [Joolee/nl.joolee.homey.espeasy#23]
Hi All,

often i use the ESP8266Wifi module for I/O functions. 

But now i want to pair a new unit but these 5 are not listed in the setup.

Is there a maximum of units to pair ?

Homey version: 5.0.4 
App version: 6.3.1.672
ESP version: 1.8.0

![image](https://user-images.githubusercontent.com/82050802/113749655-29b30f80-970a-11eb-97d3-213ad90503f6.png)

![2021-04-06 18 57 50](https://user-images.githubusercontent.com/82050802/113749697-37689500-970a-11eb-89e7-1b81df27b609.jpg)
![2021-04-06 18 52 00](https://user-images.githubusercontent.com/82050802/113749704-39caef00-970a-11eb-9182-7fc2713a8e8a.jpg)

**Comment by LoenieVincia** [comment]
I found the solution.

I add a "Generic - System Info" at Devices and now i can pair with the unit.

**Comment by Joolee** [comment]
That's the correct way. Homey checks whether you configured the ESP device correctly by waiting for 'sensor update' messages. A systeminfo device will send a few messages once every minute. I'm open to suggestions for better wording of the page in your screenshot.
