### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Just4fun-dk** [Joolee/nl.joolee.homey.espeasy#29]
Programming take hours on end and your great app and all the changes you do must have taken countless hours. Is there a way to make donations to support your work? Have you had any enquiries to make a Homey app for EspHome?

**Comment by Joolee** [comment]
Hi Just4fun. You can buy me a beer by clicking on the 'sponsor' link above the repository or 'donate' on the [app store page](https://homey.app/nl-nl/app/nl.joolee.homey.espeasy/ESP-Easy/).

I have considered switching to ESPHome but ESP Easy works for me and has very active development. Developing apps for both firmwares is a bit much for me. I do know someone else started development on an ESPHome app for Homey: https://github.com/Inversion-NL/Homey-ESPhome
