### ISSUE TITLE
ESP Easy and sensor data in Flow Card

### ISSUE THREAD

**Issue by andraves** [Joolee/nl.joolee.homey.espeasy#35]
Hello.

I have an ESP32 with two ds18b20 temperature sensors.

Sensor data only appears in Homey under the "When" Flow Card. Is it possible to get ESP Easy to show sensor data under "And" Flow Card?

**Comment by Joolee** [comment]
All sensor data is supplied by the devices in the form of a tag. You can use these tags in any place in your flow. For example, the flowing screenshot shows me accessing some information for an ESP itself. When you have added your temperature sensors to Homey, their data will be available in the same way.

![image](https://user-images.githubusercontent.com/570302/192321770-2b6a9da0-0b0a-4a71-8874-91420d34caa3.png)
