### ISSUE TITLE
Unable to detect my ESP Easy modules

### ISSUE THREAD

**Issue by Tequila329** [Joolee/nl.joolee.homey.espeasy#6]
Hi, 

first of all: great app! :) I use quite a lot of ESP8266, ES32 CAM and Wemos D1 modules. 
But the app is not able to connect to any of my devices. 
- same network
- same IP range
- some with / some without credentials
- using the ESPEasy build "mega-20191208"
-> always get a 

"Error

Could not connect to the ESP Easy unit"

Any ideas?

**Comment by Joolee** [comment]
Could you perform the pairing at https://developer.athom.com/tools/pair and send a log of the developer console of your browser (press F12 to open that) and / or send a diagnostics report from the app settings page on your phone.

Also, I'm interested in the output of your /json page of the ESP unit. Thank you in advance.

**Comment by Joolee** [comment]
Never mind, found it and fixed it in version 1.0.2

Thanks for making the report

**Comment by Tequila329** [comment]
Still no connection possible :/

**Comment by Joolee** [comment]
In that case, I'll need that debug data. Especially the /json page

**Comment by Joolee** [comment]
In your log (6ba1149a-b720-4c0a-bc15-f71fcd92e2d3), I see the following:
```
2020-05-29 10:54:45 [log] [ESPEasy] [Unit: 192.168.151.63] Fetching http://192.168.151.63:80/json
2020-05-29 10:54:49 [log] [ESPEasy] [Unit: 192.168.151.63] Error in updating json EHOSTUNREACH
```

Can you access that page when you enter the URL in a webbrowser? It looks like Homey really can't connect to your ESP unit. Are they on a different network segment?

**Comment by Joolee** [comment]
Look like there's an error in the JSON response. Can you browse to: http://10.0.1.23:80/json and post the output (if it doesn't contain anything you don't want to share)
If I know what they output, maybe I can work around it. There is also an "OK" after the JSON response from running commands so I already have to strip that off before trying to parse the JSON -_-'

You can post the output at: https://gist.github.com/ It's complaining of there being an "F" as first character so I suspect there will be no JSON at all.

**Comment by Tequila329** [comment]
> I downgraded to "mega-20191208" and cannot reproduce the problem.
> 
> In your log (6ba1149a-b720-4c0a-bc15-f71fcd92e2d3), I see the following:
> 
> ```
> 2020-05-29 10:54:45 [log] [ESPEasy] [Unit: 192.168.151.63] Fetching http://192.168.151.63:80/json
> 2020-05-29 10:54:49 [log] [ESPEasy] [Unit: 192.168.151.63] Error in updating json EHOSTUNREACH
> ```
> 
> Can you access that page when you enter the URL in a webbrowser? It looks like Homey really can't connect to your ESP unit. Are they on a different network segment?

Yes, the URL is reachable via browser. They are located at the same IP segment, but using different SSIDs to get there. No routing etc is used.

**Comment by Joolee** [comment]
It might be your access point is configured to now allow wireless clients to talk to each other. You could try making a "logic" flow card to retrieve the /json URL. See what happens.

**Comment by Joolee** [comment]
That is weird. As far as I can find, the /json page has always been part of ESP Easy. What exact build are you running? Do you see the "Show JSON" button on the tools page?

**Comment by Joolee** [comment]
Could you try: https://homey.app/a/nl.joolee.homey.espeasy/test/ I think I fixed the problem you were having.

**Comment by Tequila329** [comment]
{"System":{
"Build":20104,
"Git Build":"mega-20191208",
"System Libraries":"ESP82xx Core bc204a9b, NONOS SDK 2.2.2-dev(38a443e), LWIP: 2.1.2 PUYA support",
"Plugins":46,
"Plugin description":" [Normal]",
"Local Time":"2020-06-02 18:04:44",
"Unit Number":0,
"Unit Name":"Waeschekeller",
"Uptime":1,
"Last Boot Cause":"Manual reboot",
"Reset Reason":"Software/System restart",
"Load":10.50,
"Load LC":3490,
"CPU Eco Mode":"false",
"Heap Max Free Block":16872,
"Heap Fragmentation":5,
"Free RAM":17776
},
"WiFi":{
"Hostname":"Waeschekeller",
"IP Config":"Static",
"IP Address":"192.168.151.2",
"IP Subnet":"255.255.254.0",
"Gateway":"192.168.150.1",
"STA MAC":"EC:FA:BC:C5:9D:42",
"DNS 1":"192.168.150.1",
"DNS 2":"(IP unset)",
"SSID":"r-a-f_IoT",
"BSSID":"9E:DA:C4:96:FF:FC",
"Channel":6,
"Connected msec":72563,
"Last Disconnect Reason":1,
"Last Disconnect Reason str":"(1) Unspecified",
"Number Reconnects":0,
"Force WiFi B/G":"false",
"Restart WiFi Lost Conn":"false",
"Force WiFi No Sleep":"true",
"Periodical send Gratuitous ARP":"false",
"Connection Failure Threshold":0,
"RSSI":-69
},
"Sensors":[
{
"TaskValues": [
{"ValueNumber":1,
"Name":"Temperature",
"NrDecimals":1,
"Value":24.0
},
{"ValueNumber":2,
"Name":"Humidity",
"NrDecimals":1,
"Value":41.8
}],
"DataAcquisition": [
{"Controller":1,
"IDX":0,
"Enabled":"true"
},
{"Controller":2,
"IDX":0,
"Enabled":"false"
},
{"Controller":3,
"IDX":0,
"Enabled":"false"
}],
"TaskInterval":15,
"Type":"Environment - DHT11/12/22  SONOFF2301/7021",
"TaskName":"Umgebung",
"TaskDeviceNumber":5,
"TaskEnabled":"true",
"TaskNumber":1
},
{
"TaskValues": [
{"ValueNumber":1,
"Name":"Analog",
"NrDecimals":2,
"Value":70.00
}],
"DataAcquisition": [
{"Controller":1,
"IDX":0,
"Enabled":"true"
},
{"Controller":2,
"IDX":0,
"Enabled":"false"
},
{"Controller":3,
"IDX":0,
"Enabled":"false"
}],
"TaskInterval":60,
"Type":"Analog input - internal",
"TaskName":"MQ-7",
"TaskDeviceNumber":2,
"TaskEnabled":"true",
"TaskNumber":2
}
],
"TTL":15000
}

**Comment by Joolee** [comment]
@Tequila329 I strongly suspect this is a network issue if you still have the problem with the latest version of my app. Can you try making a flow with a "Logic" "Web request" card and the /json url? I suspect that will also fail.

**Comment by Tequila329** [comment]
I‘m not so familiar with it: anything for header and body? Method: Get?

**Comment by Joolee** [comment]
You cal leave verything default, except for the url. When you test/run the flow, you should either see a checkbox or an exclamation mark before the card.
